---
version: 2
updates:

  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      aws-sdk-go-v2:
        patterns:
          - "github.com/aws/aws-sdk-go-v2"
          - "github.com/aws/aws-sdk-go-v2/*"
      opentelemetry:
        patterns:
          - "go.opentelemetry.io/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly

  - package-ecosystem: "docker"
    directory: "/scripts/prometheus"
    schedule:
      interval: weekly
